#this code uploads files from local repo to azure storage blob

name: file upload to blob

on:
  push:
    branches: [ "main" ]

jobs:

        name : copy-files-to-blob :
        runs-on: ubuntu-latest
        steps:
      
          - name: Azure Login
            uses: azure/login@v2
            with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}
      
          - name: Azure CLI script
            uses: azure/cli@v2
            with:
              azcliversion: latest
              inlineScript: |
                az storage blob upload-batch --account-name rg1 -d test --destination path https://rg1.blob.core.windows.net/test -s ./src
  
      




   
